@startuml AdminSequence

skinparam responseMessageBelowArrow true
skinparam SequenceMessageAlignment center

actor Admin as Admin #OliveDrab

entity Task as Task #GreenYellow
entity User as User #YellowGreen

database ToDoList as ToDoList #Orange

Admin -> ToDoList: créer un compte
alt cas réussi
ToDoList-> Admin: valider création du compte
else 409 (Conflict) email déjà existant 
ToDoList-> Admin: échec de l'inscription

Admin  -> ToDoList: demander authentification 
ToDoList-> Admin: valider authentification 
else 401 (Unauthorized) identification invalides
ToDoList-> Admin: échec de l'authentification

Admin  -> User: ajouter utilisateur
User -> Admin: valider ajout
else erreur durant le traitement
User -> Admin: l'utilisateur n'a pas pu être ajouté

Admin  -> User: éditer utilisateur
User -> Admin: valider édition
else 404 (Page not found)
User -> Admin: l'utilisateur en cours de modification n'existe pas

Admin  -> User: supprimer utilisateur
User -> Admin: valider suppression
else 403 (Forbidden)
User -> Admin: Vous n'avez pas accès à cette ressource

Admin  -> Task: ajouter tâche
Task -> Admin: valider ajout
else erreur durant le traitement
Task -> Admin: la tâche n'a pas pu être ajoutée

Admin  -> Task: éditer tâche
Task -> Admin: valider édition
else 404 (Page not found)
Task -> Admin: la tâche en cours de modification n'existe pas

Admin  -> Task: supprimer tâche
Task -> Admin: valider suppression
else 403 (Forbidden)
Task -> Admin: Vous n'avez pas accès à cette ressource

Admin  -> Task: supprimer tâche anonyme
Task -> Admin: valider suppression

end
@enduml