@startuml Task

!include User.puml
!include TaskManager.puml
!include UserManager.puml

Class Task {
    
    - title : string
    - content : string
    - isDone: bool
    
}

Task *-"1" User: create <
TaskManager -- Task: exec 
UserManager -- User: exec

@enduml
