@startuml SuperAdminSequence

skinparam responseCommentBelowArrow true
skinparam SequenceCommentAlignment center

actor SuperAdmin as SuperAdmin #Plum

entity User as User #LightYellow
entity Admin as Admin #LightYellow
entity Task as Task #LightYellow

database ToDoList as ToDoList #HotPink


end
@enduml