@startuml User

left to right direction

actor "User" as user #YellowGreen

rectangle ToDoList {

  usecase "Se connecter" as UC1
  usecase "Créer ses tâches" as UC2
  usecase "Modifier ses tâches" as UC3
  usecase "Supprimer ses tâches" as UC4

}

user --> UC1
user --> UC2
user --> UC3
user --> UC4

@enduml