@startuml User

left to right direction

actor "User" as user #YellowGreen

rectangle ToDoList {

  usecase "Créer un compte" as UC1
  usecase "Se connecter" as UC2
  usecase "Créer ses tâches" as UC3
  usecase "Modifier ses tâches" as UC4
  usecase "Supprimer ses tâches" as UC5

}

user --> UC1
user --> UC2
user --> UC3
user --> UC4
user --> UC5

@enduml